- name: Install OpenJdk8, Tomcat8 Server, and  application WAR file onto server
- hosts: tomcatserver
  remote_user: ubuntu
  become: true
  tasks:
  - name: Update System Packages
    apt:
      upgrade: yes
      update_cache: yes
  - name: Install openjdk 1.8
    apt:
      name: openjdk-8-jdk
      update_cache: yes
      state: present
  - name: Validate Java installation
    shell:
      java -version
  - name: Create tomcat group
    group:
      name: tomcat
      state: present
  - name: Create tomcat user
    user:
      name: tomcat
      group: tomcat
      home: /usr/share/tomcat8
      createhome: no
      state: present
  - name: Create Tomcat directory
    file:
      path: /opt/apache-tomcat-8.0.51
      owner: tomcat
      group: tomcat
      mode: 755
      recurse: yes
  - name: Download and extract tomcat8 server application files
    unarchive:
      src: http://archive.apache.org/dist/tomcat/tomcat-8/v8.0.51/bin/apache-tomcat-8.0.51.tar.gz
      dest: /opt/apache-tomcat-8.0.51
      remote_src: yes
  - name: Change ownership of tomcat installation directory
    file:
      path: /opt/apache-tomcat-8.0.51
      owner: tomcat
      group: tomcat
      mode: 0755
      recurse: yes
      state: directory
  - name: Create Symlink to tomcat installation directory
    file:
      src: /opt/apache-tomcat-8.0.51
      path: /usr/share/tomcat8
      state: link
      owner: tomcat
      group: tomcat
      mode: 0755
  - name: Copy WAR file
    copy:
      src: ./target/addressbook.war
      dest: /opt/apache-tomcat-8.0.51/webapps/ROOT.war
      owner: tomcat
      group: tomcat
  - name: Copy Tomcat service from local to remote_src
    copy:
      src: /etc/tomcat.service
      dest: /etc/systemd/system/
      mode: 0755
  - name: Reload the SystemD to re-read configurations
    systemd:
      daemon_reload: true
  - name: Enable the tomcat service and start
    systemd:
      name: tomcat
      enabled: yes
      state: started
