---
- hosts: tomcatserver
  remote_user: ubuntu
  become: true
  tasks:
  - name: Update System Packages
    apt:
      upgrade: yes
      update_cache: no
  - name: Create tomcat group
    group:
      name: tomcat
      state: present
  - name: Create tomcat user
    user:
      name: tomcat
      group: tomcat
      home: /usr/share/tomcat8
      createhome: no
      state: present
  - name: Download tomcat8 server application files
    get_url:
      url: http://archive.apache.org/dist/tomcat/tomcat-8/v8.0.51/bin/apache-tomcat-8.0.51.tar.gz
      dest: /opt/apache-tomcat-8.0.51.tar.gz
  - name: Extract tomcat8 server application files
    command: tar zxvf /opt/apache-tomcat-8.0.51.tar.gz -C /opt/ creates=/opt/apache-tomcat-8.0.51
  - name: Change ownership of tomcat installation directory
    file:
      path: /opt/apache-tomcat-8.0.51
      owner: tomcat
      group: tomcat
      mode: 0755
      recurse: yes
      state: directory
  - name: Create Symlink to tomcat installation directory
    file:
      src: /opt/apache-tomcat-8.0.51
      path: /usr/share/tomcat8
      state: link
      owner: tomcat
      group: tomcat
      mode: 0755
  - name: Copy application war file
    copy:
      src: ./target/addressbook.war
      dest: /opt/apache-tomcat-8.0.51/webapps/ROOT.war
      owner: tomcat
      group: tomcat
      mode: 0755
  - name: Creating a service file
    copy: 
      content: |-
        [Unit]
        Description=Tomcat Service
        Requires=network.target
        After=network.target
        [Service]
        Type=forking
        User=tomcat
        Environment="CATALINA_PID=/opt/apache-tomcat-8.0.51/logs/tomcat.pid"
        Environment="CATALINA_BASE=/opt/apache-tomcat-8.0.51"
        Environment="CATALINA_HOME=/opt/apache-tomcat-8.0.51"
        Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
        ExecStart=/opt/apache-tomcat-8.0.51/bin/startup.sh
        ExecStop=/opt/apache-tomcat-8.0.51/bin/shutdown.sh
        Restart=on-abnormal
        [Install]
        WantedBy=multi-user.target
      dest: /etc/systemd/system/tomcat.service
  - name: Reload the SystemD to re-read configurations
    systemd:
      daemon-reload: yes
  - name: Enable the tomcat service and start
    systemd:
      name: tomcat
      enabled: yes
      state: started
  - name: Connect to Tomcat server on port 8080 and check status 200 - Try 5 times
    tags: test
    uri:
      url: http://localhost:8080
    register: result
    until: "result.status == 200"
    retries: 5
    delay: 10
...
